const $=s=>document.querySelector(s), E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const views=[['overview','▦','공정 모니터'],['orders','▤','생산 주문'],['inventory','▧','부품·창고'],['approvals','✓','승인·보고'],['signals','⌁','설비·태그'],['feedback','↺','운영 피드백']];
let state=null,view='overview',selectedUnit='',filter='',groupFilter='',busy=false,previousTags={},changed=new Set();
const roles={operator:'작업자',admin:'관리자'}, models={VAN:'밴',TRUCK:'트럭'},lamps={ROUND:'라운드',ANGULAR:'각진형'},seats={COCOA:'cocoabrown',DARK:'darkbrown'};
const unitName=u=>u.state==='completed'&&u.external_source?'SCADA 생산 완료':names[u.state];
const names={external_running:'SCADA 생산 중 · 공정 대응 대기',failed_final:'최종 NG · 재생산 등록',resupply_pending:'NG 부품 · 재공급 대기',cancelled:'최종 NG · 주문 종료',planned:'공급 대기',running:'공정 진행',ng:'NG · 수리 대기',awaiting_approval:'승인 대기',rejected:'반려',completed:'적재 완료',return_vision4:'리턴 종류검사',return_robot4:'리턴 창고 이동',returned:'리턴 완료',waiting:'승인 중',approved:'승인 완료'};
const badge=(label,color='')=>`<span class="badge ${color}">${E(label)}</span>`;
const stateColor=s=>['ng','rejected','failed_final'].includes(s)?'red':s==='awaiting_approval'||s==='waiting'?'orange':['completed','approved','returned'].includes(s)?'green':s==='running'?'blue':'';
const dt=v=>v?new Date(v.replace(' ','T')+(v.endsWith('Z')?'':'Z')).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'—';
const tag=(table,name)=>state?.live.tags[table]?.find(t=>t.tag_name===name),num=(table,name)=>tag(table,name)?.value_number??null;
const flag=(table,name)=>tag(table,name)?.status_code===0&&Boolean(num(table,name));
const liveOK=()=>state?.live.connected&&state?.collector.connected&&state?.collector.fresh;
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast visible'+(error?' error':'');clearTimeout(el.timer);el.timer=setTimeout(()=>el.className='toast',5000)}
function renderNav(){$('#navigation').innerHTML=views.map(([id,icon,label])=>`<button data-view="${id}" class="${view===id?'active':''}" aria-current="${view===id?'page':'false'}"><span class="nav-symbol">${icon}</span>${label}${id==='approvals'&&state?.approvals.some(a=>a.state==='waiting')?' '+badge(state.approvals.filter(a=>a.state==='waiting').length,'orange'):''}</button>`).join('')}
function heading(title,subtitle,action=''){return `<div class="page-heading"><div><div class="eyebrow">MANUFACTURING / TEAM 2</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div>${action}</div>`}
function panel(title,body,meta='',classes=''){return `<section class="panel ${classes}"><div class="panel-head"><h2>${title}</h2>${meta}</div>${body}</section>`}
function equipment(kind,index){let table=kind==='robot'?'team2-robotdb':'team2-vision',prefix=kind==='robot'?'ROBOT':'VISION'+index;let suffix=kind==='robot'?`_(${index})`:'';const key=t=>kind==='robot'?`ROBOT_${t}${suffix}`:`${prefix}_${t}`;let status='대기',color='',cls='';
 if(!liveOK()){status='통신 확인';color='orange'}else if(flag(table,key('ERROR'))){status='설비 오류';color='red';cls='error'}else if(kind==='vision'&&flag(table,key('NG'))){status='NG';color='red';cls='error'}else if(flag(table,key('RUNNING'))){status='작업 중';color='blue';cls='running'}else if(flag(table,key('FINISH'))){status='완료 신호';color='green';cls='done'}else if(kind==='robot'&&flag(table,key('READY'))){status='준비 완료';color='green'}
 const description=kind==='robot'?['램프 조립','시트 조립','바디 조립','리턴 창고 이동'][index-1]:['램프 조립전 검사','시트 조립전 검사','최종 조립검사','리턴 종류검사'][index-1];
 return `<div class="equipment ${cls}"><div class="equipment-head"><span class="equipment-name">${kind==='robot'?'로봇':'비전'} ${index}</span>${badge(status,color)}</div><p>${description}</p></div>`}
function inventoryMini(){return state.inventory.filter(i=>i.item_id!=='FINISHED').map(i=>`<div class="inventory-mini"><div class="inventory-row"><span>${E(i.label)}</span><strong>${i.quantity} <span class="text-muted">/ ${i.capacity}</span></strong></div><div class="bar ${i.quantity<=1?'low':''}"><span style="width:${100*i.quantity/i.capacity}%"></span></div></div>`).join('')}
function currentUnit(){if(!selectedUnit||!state.units.some(u=>u.unit_id===selectedUnit))selectedUnit=state.units.find(u=>!['completed','returned','cancelled','failed_final'].includes(u.state))?.unit_id||state.units[0]?.unit_id||'';return state.units.find(u=>u.unit_id===selectedUnit)}
function unitActions(u){if(!u)return '';if(u.state==='resupply_pending')return `<button class="primary" data-act="resupply" data-id="${E(u.unit_id)}">NG 부품 리턴·1개 재공급 확인</button>`;if(['planned','running'].includes(u.state)){const s=state.stages[u.stage];if(!s)return '';return `<button class="primary" data-act="advance" data-id="${E(u.unit_id)}">${u.stage===0?'공급 확인':s[0].startsWith('VISION')?'검사 결과 입력':'완료 확인'}</button>`}if(u.state==='awaiting_approval')return `<button data-view="approvals">승인 요청 보기</button>`;if(['ng','rejected'].includes(u.state))return `<button data-act="repair" data-id="${E(u.unit_id)}">수리 완료 접수</button>`;if(u.state==='return_vision4')return `<button data-act="classify" data-id="${E(u.unit_id)}">리턴 종류·위치 확인</button>`;if(u.state==='return_robot4')return `<button data-act="store" data-id="${E(u.unit_id)}">로봇4 이동 완료 확인</button>`;return badge(unitName(u),stateColor(u.state))}
function processPanel(){const u=currentUnit();if(!u)return panel('제품별 공정 진행',`<div class="empty"><strong>아직 등록된 MES 주문이 없습니다</strong>주문을 등록하면 제품마다 추적번호와 공정 확인 기록이 생성됩니다.<br>설비의 실제 신호는 아래에서 확인할 수 있습니다.<br><button class="primary" data-act="new-order">주문 등록</button></div>`,badge('작업자 확인 기록'));
 const order=state.orders.find(o=>o.order_id===u.order_id),progress=Math.round((u.confirmed_stages||[]).filter(c=>state.stages.some(s=>s[0]===c)).length/8*100);
 const tiles=state.stages.map(([code,label],i)=>`<div class="stage ${(u.confirmed_stages||[]).includes(code)?'done':i===u.stage?['ng','resupply_pending','cancelled','failed_final'].includes(u.state)?'ng':'active':''}"><div class="stage-num">${String(i+1).padStart(2,'0')} / ${code}</div><div class="stage-label">${label}</div><small>${(u.confirmed_stages||[]).includes(code)?'✓ 확인 완료':i<u.stage?'등록 이전 · 미확인':i===u.stage?unitName(u):'대기'}</small></div>`).join('');
 return panel('제품별 공정 진행',`<div class="panel-body"><div class="process-selector"><select id="unit-selector" aria-label="진행 제품 선택">${state.units.map(x=>`<option value="${E(x.unit_id)}" ${x.unit_id===u.unit_id?'selected':''}>${E(x.unit_id)} · ${unitName(x)}</option>`).join('')}</select>${badge(models[order?.model]||'—','blue')}${badge(progress+'% 확인')}</div><p class="subtitle">${E(lamps[order?.lamp])} 램프 · ${E(seats[order?.seat])} 시트 ${order?.model==='VAN'?2:1}개 · MES 기록${u.stage===3||u.stage===4?' · 시트 '+(u.seat_completed+1)+'/'+u.seat_required+' 검사·조립':''}</p><div class="progress-track"><span style="width:${progress}%"></span></div><div class="pipeline">${tiles}</div><div class="action-strip"><div><strong>${E(u.unit_id)} · ${unitName(u)}</strong><p>제품별 진행은 작업자 확인으로 기록합니다. PLC의 제품 추적 ID 연결은 정의 대기입니다.</p></div><div class="action-buttons">${unitActions(u)}</div></div>${['ng','rejected','return_vision4','return_robot4','returned'].includes(u.state)?'<div class="return-flow"><span><strong>수리품 리턴</strong>':'<div class="return-flow"><span><strong>검사 NG 처리</strong>'}<br>${['ng','rejected','return_vision4','return_robot4','returned'].includes(u.state)?'수리 완료 접수 → 비전4 종류검사 → 로봇4 창고 이동':'비전1·2: 해당 부품 1개 리턴·재공급 → 재검사 / 비전3: 다음 예정 제품 뒤에 우선 재생산'}</span><span>${u.return_location?'목적지: '+E(u.return_location):['ng','rejected','return_vision4','return_robot4','returned'].includes(u.state)?'창고 위치는 리턴 접수 시 확인':'NG 이력 보존'}</span></div></div>`,badge('작업자 확인 기록'))}
function overview(){const finished=state.inventory.find(i=>i.item_id==='FINISHED'),today=num('team2-order','TODAY_COMPLETED_COUNT'),pending=state.approvals.filter(a=>a.state==='waiting').length,ng=state.units.filter(u=>['ng','rejected','return_vision4','return_robot4','resupply_pending'].includes(u.state)).length;
 return heading('공정 모니터','공정 진행과 검사·설비 상태를 한눈에 확인합니다.',`<div class="action-buttons"><button data-act="adopt">이미 생산 중인 제품 등록</button><button class="primary" data-act="new-order">＋ 주문 등록</button></div>`)+`<div class="kpis"><div class="kpi"><div class="kpi-label">오늘 생산 완료</div><div class="kpi-value">${today??'—'}<small>대</small></div><div class="kpi-foot">PLC TODAY_COMPLETED_COUNT ${!liveOK()?'· 마지막 저장값':''}</div></div><div class="kpi"><div class="kpi-label">승인 대기</div><div class="kpi-value">${pending}<small>건</small></div><div class="kpi-foot">최종검사 OK 시 관리자 기본승인</div></div><div class="kpi"><div class="kpi-label">NG · 리턴 처리</div><div class="kpi-value">${ng}<small>대</small></div><div class="kpi-foot">MES에 기록된 처리 대상</div></div><div class="kpi"><div class="kpi-label">완료창고 적재</div><div class="kpi-value">${finished?.quantity??0}<small>/ 6대</small></div><div class="kpi-foot">작업자 확인 수량</div></div></div><div class="columns"><div>${processPanel()}${panel('실시간 설비 상태',`<div class="panel-body"><div class="equipment-grid">${[1,2,3,4].map(i=>equipment('robot',i)).join('')}${[1,2,3,4].map(i=>equipment('vision',i)).join('')}</div><div class="line-status section-gap">${['PLC_Emergency','PLC_Emergency_botten','SERVO_BUSY','JIG_Dispose'].map(n=>badge(n+' '+(num('team2-plcstatus',n)===null?'—':flag('team2-plcstatus',n)?'ON':'OFF'),flag('team2-plcstatus',n)&&n.includes('Emergency')?'red':'')).join('')}</div></div>`,badge(liveOK()?'실시간 · 3초 갱신':'마지막 저장값',liveOK()?'green':'orange'))}</div><div class="side-panels">${panel('부품 공급창고',`<div class="panel-body">${inventoryMini()}<p class="mini-foot">수기 재고 · 밴은 시트 2개, 트럭은 1개<br>샤시 0개 시 1개 보충 확인 필요</p><button class="small section-gap" data-view="inventory">재고 관리 →</button></div>`,badge('수기'))}${panel('완료창고',`<div class="panel-body"><div class="warehouse-slots">${Array.from({length:6},(_,i)=>`<div class="slot ${i<(finished?.quantity||0)?'occupied':''}"><div>${i<(finished?.quantity||0)?'<div class="vehicle">▰</div>':'빈 위치'}<br>${String(i+1).padStart(2,'0')}</div></div>`).join('')}</div><p class="mini-foot">최대 6대 · 출고 후 수량을 확인하세요.</p></div>`,badge(`${finished?.quantity||0} / 6`))}</div></div>${panel('최근 공정 확인',eventTable(state.events.slice(0,6)),`<span class="panel-note">작업자 확인 이력</span>`)}`;
}
function eventTable(events){if(!events.length)return '<div class="empty">공정 확인 기록이 아직 없습니다.</div>';return `<div class="table-wrap"><table><thead><tr><th>시각</th><th>제품</th><th>공정</th><th>결과</th><th>기록자</th></tr></thead><tbody>${events.map(x=>`<tr><td>${dt(x.occurred_at)}</td><td>${E(x.unit_id)}</td><td>${E(x.stage_code)}</td><td>${badge(x.result,x.result==='NG'?'red':'green')}</td><td>${E(x.operator_name)}<small>${E(x.note)}</small></td></tr>`).join('')}</tbody></table></div>`}
function scadaPanel(){const sync=state.scada_sync;return panel('SCADA 주문 연동',`<div class="panel-body"><div class="line-status">${badge(sync?.connected?'원본 DB 연결 정상':'원본 DB 확인 필요',sync?.connected?'green':'red')}${badge('전체 연결 '+(sync?.linked_orders||0)+'건')}${badge('현재 모드 '+state.external_orders.length+'건')}</div><p class="mini-foot">smart_factory.orders → MES 주문번호 · 기존 104건 TEST · 신규 주문은 MES GUI 모드로 등록<br>생산 시작시각 기준 번호 / 시작 전이면 주문시각 사용 · 원본 시각·번호 보존 · 과거 완료품 재고는 가산하지 않음</p>${sync?.error?'<div class="notice red">'+E(sync.error)+'</div>':''}</div>`)}
function queuePanel(){return panel('생산 대기 순서',`<div class="panel-body"><p class="subtitle">최종 NG 재생산은 다음 예정 제품 뒤, 나머지 일반 주문 앞에 배치합니다. 이미 진행 중인 생산은 중단하지 않습니다.</p>${state.queue.length?'<ol>'+state.queue.map(q=>'<li>'+E(q.unit_id)+' '+badge(q.kind==='REMAKE'?'우선 재생산':'일반 주문',q.kind==='REMAKE'?'orange':'')+'</li>').join('')+'</ol>':'<p class="mini-foot">대기 제품 없음</p>'}<p class="mini-foot">SCADA 재생산 큐 쓰기 연결 대기 · 큐 변경을 mes_scada_outbox에 저장합니다.</p></div>`)}
function orders(){let list=state.orders.filter(o=>o.order_id.toLowerCase().includes(filter.toLowerCase()));return heading('생산 주문','주문 구성과 제품별 공정·검사 이력을 관리합니다.',`<div class="action-buttons"><button data-act="adopt">이미 생산 중인 제품 등록</button><button class="primary" data-act="new-order">＋ 주문 등록</button></div>`)+`<div class="notice orange">PLC 주문 전송은 프로그램 번호 매핑과 START/ACK 핸드셰이크 정의 대기입니다. 현재 주문 등록은 MES 기록이며 설비를 작동시키지 않습니다.</div><div class="toolbar"><input id="search" aria-label="주문 검색" placeholder="주문번호 검색" value="${E(filter)}"><span class="stat-chip">등록 주문<strong>${state.orders.length}</strong></span></div>${scadaPanel()}${queuePanel()}${panel('주문 목록',list.length?`<div class="table-wrap"><table><thead><tr><th>주문번호</th><th>제품 구성</th><th>수량 / 완료</th><th>PLC 프로그램</th><th>상태</th><th></th></tr></thead><tbody>${list.map(o=>{const external=state.external_orders.find(x=>x.mes_order_id===o.order_id),source=external?JSON.parse(external.source_payload):null;const units=state.units.filter(u=>u.order_id===o.order_id),complete=units.filter(u=>u.state==='completed').length,waiting=units.filter(u=>u.state==='awaiting_approval').length;return `<tr><td><strong>${E(o.order_id)}</strong><small>${dt(o.created_at)} · ${E(o.operator_name)}</small>${external?'<small>SCADA #'+E(external.source_order_id)+' · '+E(source.status)+' · 완료 '+source.completed_qty+'/'+source.order_qty+'<br>생산 시작 '+dt(external.source_produced_at)+'</small>':''}</td><td>${models[o.model]}<small>${lamps[o.lamp]} / ${seats[o.seat]}</small></td><td class="table-number">${o.quantity} / ${complete}</td><td>${o.program_no??'매핑 대기'}<small>PLC 전송 미연결</small></td><td>${badge(complete===o.quantity?(source?'SCADA 생산 완료':'적재 완료'):waiting?'승인 대기':units.some(u=>u.state==='failed_final')?'재생산 추적 중':units.some(u=>u.state==='cancelled')?'기존 종료 기록':units.some(u=>u.state==='resupply_pending')?'부품 재공급 대기':units.every(u=>u.state==='returned')?'리턴 완료':'공정 대기·진행',complete===o.quantity?'green':waiting?'orange':'blue')}</td><td><button class="small" data-act="select-unit" data-id="${E(units[0]?.unit_id)}">공정 보기</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">등록된 주문이 없습니다. 주문 구성부터 입력하세요.</div>')}${panel('제품 추적 목록',state.units.length?`<div class="table-wrap"><table><thead><tr><th>제품 추적번호</th><th>현재 공정</th><th>상태</th><th>리턴 위치</th><th>작업</th></tr></thead><tbody>${state.units.map(u=>`<tr><td>${E(u.unit_id)}</td><td>${u.stage>=8?'완료':E(state.stages[u.stage]?.[1]||'—')}</td><td>${badge(unitName(u),stateColor(u.state))}</td><td>${E(u.return_location||'—')}</td><td>${unitActions(u)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">주문 등록 시 제품 추적번호가 생성됩니다.</div>')}`}
function inventory(){return heading('부품·창고','공급·입고·출고 시 수량을 확인하고 기록합니다.')+`<div class="notice">초기 수량은 제공해주신 창고 구성에서 시작했습니다. 현재 재고 태그가 연결되지 않아 수기 재고로 관리합니다. 샤시는 0개가 되면 1개 보충을 확인하세요.</div><div class="inventory-grid">${state.inventory.map(i=>`<section class="inventory-card"><div class="inventory-icon">${i.item_id==='FINISHED'?'▥':'▧'}</div><h3>${E(i.label)}</h3><div class="inventory-count">${i.quantity}<small> / ${i.capacity}${i.item_id.startsWith('SEAT')?'개':'대'}</small></div><div class="bar ${i.quantity<=1?'low':''}"><span style="width:${i.quantity/i.capacity*100}%"></span></div><p>${i.source==='USER_INITIAL'?'제공된 초기 수량':'작업자 확인 수량'} · ${dt(i.updated_at)}<br>${i.item_id==='CHASSIS'?'0개 시 1개씩 보충 확인':i.item_id==='FINISHED'?'서보 적재 완료 확인 시 +1 · 출고 후 수기 확인':'공급 확인 시 제품 1대분 차감'}</p><button data-act="inventory" data-id="${E(i.item_id)}">수량 확인·입출고</button></section>`).join('')}</div>`}
function approvals(){const admin=$('#role').value==='admin',pending=state.approvals.filter(a=>a.state==='waiting');return heading('승인·보고','검사 확인 → 승인 요청 → PDF 발행 → ERP 전송 대기')+`<div class="notice">현재 승인 규칙: 최종검사 OK 확인 시 관리자 기본 자동승인, 승인 후 적재 가능. 승인자는 화면 모드를 전환할 수 있는 학습용 방식입니다. ERP 연결 전까지 전송 대기 기록을 보관합니다.</div>${!admin?'<div class="notice orange">작업자 화면입니다. 승인·반려는 상단 화면을 관리자로 전환하면 사용할 수 있습니다.</div>':''}<div class="kpis"><div class="kpi"><div class="kpi-label">승인 대기</div><div class="kpi-value">${pending.length}</div></div><div class="kpi"><div class="kpi-label">승인 완료</div><div class="kpi-value">${state.approvals.filter(a=>a.state==='approved').length}</div></div><div class="kpi"><div class="kpi-label">반려</div><div class="kpi-value">${state.approvals.filter(a=>a.state==='rejected').length}</div></div><div class="kpi"><div class="kpi-label">발행 보고서</div><div class="kpi-value">${state.reports.length}</div></div></div>${panel('검사 승인 요청',state.approvals.length?`<div class="table-wrap"><table><thead><tr><th>제품</th><th>요청 / 대기시간</th><th>상태</th><th>승인자 / 사유</th><th>처리</th></tr></thead><tbody>${state.approvals.map(a=>{let minutes=Math.max(0,Math.floor((Date.now()-new Date(a.requested_at.replace(' ','T')+'Z'))/60000));return `<tr><td><strong>${E(a.unit_id)}</strong><small>최종검사 OK · 수기 확인</small></td><td>${dt(a.requested_at)}<small>${a.state==='waiting'?minutes+'분 대기':dt(a.decided_at)}</small></td><td>${badge(names[a.state],stateColor(a.state))}</td><td>${E(a.approver||'—')}<small>${E(a.reason)}</small></td><td>${a.state==='waiting'?`<div class="table-actions"><button class="small success" data-act="approve" data-id="${a.approval_id}" ${!admin?'disabled':''}>승인</button><button class="small danger" data-act="reject" data-id="${a.approval_id}" ${!admin?'disabled':''}>반려</button></div>`:'처리 완료'}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">최종검사 OK를 확인하면 승인 요청이 자동 생성됩니다.</div>')}${panel('발행 보고서 · ERP 연계',state.reports.length?`<div class="table-wrap"><table><thead><tr><th>보고서</th><th>발행 시각</th><th>ERP</th><th>파일</th></tr></thead><tbody>${state.reports.map(r=>{let a=state.approvals.find(a=>a.approval_id===r.approval_id);return `<tr><td>최종검사 승인<small>${E(a?.unit_id)}</small></td><td>${dt(r.created_at)}</td><td>${badge(r.run_mode==='TEST'?'테스트 기록':'연결 설정 대기','orange')}<small>전송되지 않음</small></td><td><a class="report-link" href="/reports/${r.filename}" target="_blank">PDF 열기 ↗</a></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">최종검사 OK 확인 시 관리자 기본승인과 PDF 발행이 자동으로 진행됩니다.</div>')}`}
function signals(){let tags=Object.entries(state.live.tags).flatMap(([group,items])=>items.map(t=>({...t,group}))).filter(t=>(!groupFilter||t.group===groupFilter)&&t.tag_name.toLowerCase().includes(filter.toLowerCase()));return heading('설비·태그','PLC에서 수집한 원본 값과 품질·수신 시각을 확인합니다.')+`<div class="toolbar"><input id="search" aria-label="태그 검색" placeholder="태그 이름 검색" value="${E(filter)}"><select id="group-filter" aria-label="설비 그룹"><option value="">전체 설비</option>${['team2-robotdb','team2-vision','team2-order','team2-plcstatus'].map(g=>`<option ${g===groupFilter?'selected':''}>${g}</option>`).join('')}</select><span class="tag-count">${tags.length}개 태그</span></div>${panel('실시간 신호',`<div class="table-wrap"><table><thead><tr><th>설비 그룹</th><th>태그</th><th>값</th><th>품질 / 저장 모드</th><th>마지막 값 수신</th></tr></thead><tbody>${tags.map(t=>`<tr class="${changed.has(t.group+'/'+t.tag_name)?'pulse':''}"><td>${t.group}</td><td>${E(t.tag_name)}</td><td class="signal-value">${E(t.value_text)}</td><td>${badge(t.status_code===0?'Good':'Bad '+t.status_code,t.status_code===0?'green':'red')}<small>${t.collection_mode==='PRODUCTION'?'생산':t.collection_mode==='TEST'?'공정테스트':'기존 이력'}</small></td><td>${dt(t.received_at)}</td></tr>`).join('')}</tbody></table></div>`,badge(liveOK()?'수집기 연결 정상':'연결 확인 필요',liveOK()?'green':'orange'))}<p class="mini-foot">마지막 값 수신 시각은 값 변경이 저장된 시각입니다. 값이 변하지 않으면 시각도 그대로입니다. 초록색 배경은 방금 변경된 값을 나타냅니다.</p>`}
function feedback(){return heading('운영 피드백','현장 오류, 승인 지연 원인, 개선 의견을 기록합니다.')+`<div class="columns"><div>${panel('피드백 기록',`<div class="panel-body"><div class="feedback-list">${state.feedback.length?state.feedback.map(f=>`<div class="feedback-item"><strong>${E(f.operator_name)}</strong> <span class="panel-note">${dt(f.created_at)}</span><p>${E(f.message)}</p></div>`).join(''):'<div class="empty">등록된 피드백이 없습니다.</div>'}</div></div>`)}</div><div>${panel('현장 의견 남기기',`<form id="feedback-form" class="panel-body"><label class="form-label">내용<textarea name="message" maxlength="2000" required placeholder="어느 공정에서 무엇이 불편했나요?"></textarea></label><button class="primary section-gap" type="submit">피드백 등록</button></form><div class="notice">승인 대기시간은 승인·보고 화면에서 확인할 수 있습니다. 설비 통신 오류는 상단 상태와 설비·태그 화면에서 확인하세요.</div>`)}${panel('연결 상태',`<div class="panel-body stack"><span>${badge(state.live.connected?'DB 읽기 정상':'DB 읽기 실패',state.live.connected?'green':'red')}</span><span>${badge(liveOK()?'OPC UA 수집기 정상':'OPC UA 수집기 확인 필요',liveOK()?'green':'orange')}</span><p class="subtitle">${E(state.live.error||'DB·수집기 상태를 주기적으로 확인하고 있습니다.')}</p></div>`)}</div></div>`}
function render(){if(!state)return;renderNav();$('#mode-test').classList.toggle('selected',state.mode==='TEST');$('#mode-production').classList.toggle('selected',state.mode==='PRODUCTION');$('#mode-test').setAttribute('aria-pressed',state.mode==='TEST');$('#mode-production').setAttribute('aria-pressed',state.mode==='PRODUCTION');$('#connection').innerHTML=`<span class="connection-dot ${liveOK()?'':'offline'}"></span>${liveOK()?'설비 데이터 연결 정상':'연결 확인 필요'} <span class="panel-note">· ${Object.values(state.live.tags).reduce((a,b)=>a+b.length,0)} 태그</span>`;
 let alerts=[];if(!state.live.connected)alerts.push('DB 연결 실패: '+state.live.error);else if(!liveOK())alerts.push('OPC UA 수집기 연결을 확인하세요. 설비 값은 마지막 저장값입니다.');if(liveOK()&&(flag('team2-plcstatus','PLC_Emergency')||flag('team2-plcstatus','PLC_Emergency_botten')))alerts.push('PLC 비상정지 신호가 감지됐습니다. 현장 상태를 확인하세요.');$('#alert').innerHTML=alerts.map(x=>`<div class="notice red">${E(x)}</div>`).join('');
 const focused=document.activeElement;if(focused&&$('#main').contains(focused)&&['INPUT','TEXTAREA','SELECT'].includes(focused.tagName))return;
 $('#main').innerHTML=({overview,orders,inventory,approvals,signals,feedback}[view]||overview)();}
async function refresh(){if(busy)return;busy=true;try{const r=await fetch('/api/state');const data=await r.json();if(!r.ok)throw Error(data.error);state=data;changed=new Set();Object.entries(state.live.tags).forEach(([g,items])=>items.forEach(t=>{let key=g+'/'+t.tag_name;if(previousTags[key]!==undefined&&previousTags[key]!==t.value_text)changed.add(key);previousTags[key]=t.value_text}));render()}catch(e){$('#connection').innerHTML='<span class="connection-dot offline"></span>화면 서버 연결 실패';$('#alert').innerHTML=`<div class="notice red">${E(e.message)} · 잠시 후 다시 확인합니다.</div>`}finally{busy=false}}
async function mutate(path,payload){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,operator:$('#operator').value,role:$('#role').value})});const data=await r.json();if(!r.ok)throw Error(data.error);toast(data.message);$('#modal').close();await refresh();return data}
function modal(content){$('#modal-body').innerHTML=content;$('#modal').showModal()}
function form(title,body,submitLabel='확인·기록'){return `<div class="form-title"><h2>${title}</h2></div><form id="action-form">${body}<div class="form-footer"><button type="button" data-act="close">취소</button><button class="primary" type="submit">${submitLabel}</button></div></form>`}
function handleAction(act,id){if(act==='close')return $('#modal').close();if(act==='select-unit'){selectedUnit=id;view='overview';render();return}let u=state.units.find(u=>u.unit_id===id);
 if(act==='mode-test'||act==='mode-production'){mutate('mode',{mode:act==='mode-test'?'TEST':'PRODUCTION'}).catch(e=>toast(e.message,true));return}
 if(act==='new-order'||act==='adopt'){modal(form(act==='adopt'?'이미 생산 중인 제품 등록':'생산 주문 등록',`<div class="form-grid"><div class="wide notice">MES 주문번호는 <strong>날짜시간 + 제품 옵션</strong>으로 자동 생성합니다.<br>B=darkbrown / C=cocoabrown · A=라운드 / B=각진 램프</div><label>차종<select name="model" required><option value="">선택하세요</option><option value="VAN">밴 · 시트 2개</option><option value="TRUCK">트럭 · 시트 1개</option></select></label><label>주문 수량<input name="quantity" type="number" min="1" max="100" value="1" required></label><label>램프<select name="lamp" required><option value="">선택하세요</option><option value="ROUND">라운드형</option><option value="ANGULAR">각진형</option></select></label><label>시트 색상<select name="seat" required><option value="">선택하세요</option><option value="COCOA">cocoabrown</option><option value="DARK">darkbrown</option></select></label>${act==='adopt'?'<label class="wide">현재 진행 중인 공정<select name="initial_stage">'+state.stages.slice(0,7).map((st,i)=>'<option value="'+i+'">'+st[1]+' 대기·진행</option>').join('')+'</select><small>등록 이전의 공정 완료 및 재고 차감은 추정하지 않습니다.</small></label>':''}<label class="wide">PLC 프로그램 번호 (선택)<input name="program_no" type="number" min="0" max="65535" placeholder="매핑 확인 후 입력"><small>현재 MES 등록만 가능 · PLC 자동 전송 정의 대기</small></label></div>`,'MES 주문 등록'));$('#action-form').onsubmit=submit('orders',{adopt:act==='adopt'});return}
 if(act==='resupply'){modal(form('NG 부품 리턴·동일 부품 1개 재공급 확인',`<div class="notice">NG 부품이 리턴컨베이어로 이동하고 같은 옵션의 부품 1개가 재공급되었는지 확인하세요. 재공급 부품만 1개 추가 차감하며 같은 검사 단계로 돌아갑니다.</div><label class="form-label">확인 메모<textarea name="note" maxlength="500"></textarea></label>`));$('#action-form').onsubmit=submit('resupply',{unit_id:id});return}
 if(act==='advance'){const stage=state.stages[u.stage];modal(form(`${E(u.unit_id)} · ${stage[1]}`,`<div class="notice">이 확인은 MES 공정·재고 기록에 반영됩니다. 설비 제어 신호는 전송하지 않습니다.</div><div class="form-grid">${stage[0].startsWith('VISION')?'<label class="wide">검사 결과<select name="result"><option value="OK">OK · 다음 단계</option><option value="NG">NG · 수리 대기</option></select></label>':'<input name="result" type="hidden" value="OK">'}<label class="wide">확인 메모<textarea name="note" maxlength="1000" placeholder="NG라면 원인을 입력하세요"></textarea></label></div>`));$('#action-form').onsubmit=submit('advance',{unit_id:id});return}
 if(['repair','classify','store'].includes(act)){modal(form(act==='repair'?'수리 완료품 접수':act==='classify'?'비전4 종류·위치 확인':'로봇4 창고 이동 완료',`<p class="subtitle">${E(id)}</p><div class="form-grid section-gap">${act==='classify'?'<label class="wide">리턴 창고 위치<input name="location" required maxlength="100" placeholder="예: 리턴창고 A-01"></label>':''}<label class="wide">확인 메모<textarea name="note" maxlength="1000"></textarea></label></div><div class="notice">수리·리턴 제품의 추적 기록을 남깁니다. 부품 공급창고 재고를 자동 가산하지 않습니다.</div>`));$('#action-form').onsubmit=submit('return',{unit_id:id,action:act});return}
 if(['approve','reject'].includes(act)){modal(form(act==='approve'?'최종검사 승인':'최종검사 반려',`<p class="subtitle">${E(state.approvals.find(a=>a.approval_id===id)?.unit_id)}</p><label class="form-label section-gap">${act==='reject'?'반려 사유 (필수)':'승인 메모'}<textarea name="reason" maxlength="1000" ${act==='reject'?'required':''}></textarea></label>${act==='approve'?'<div class="notice">승인 후 PDF를 자동 발행하고 적재 확인을 활성화합니다. ERP는 전송 대기로 기록됩니다.</div>':''}`,act==='approve'?'승인·PDF 발행':'반려 기록'));$('#action-form').onsubmit=submit('approval',{approval_id:id,decision:act==='approve'?'approved':'rejected'});return}
 if(act==='inventory'){let i=state.inventory.find(i=>i.item_id===id);modal(form(E(i.label)+' 수량 확인',`<div class="form-grid"><label>실제 확인 수량<input name="quantity" type="number" min="0" max="${i.capacity}" value="${i.quantity}" required></label><label class="wide">입고·출고·실사 사유<textarea name="reason" required maxlength="1000" placeholder="예: 샤시 0개 확인 후 1개 보충"></textarea></label></div>`));$('#action-form').onsubmit=submit('inventory',{item_id:id});return}}
function submit(path,extra={}){return async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await mutate(path,{...Object.fromEntries(new FormData(e.target)),...extra})}catch(error){toast(error.message,true)}finally{button.disabled=false}}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-view],[data-act]');if(!el)return;if(el.dataset.view){view=el.dataset.view;filter='';render();window.scrollTo(0,0)}else handleAction(el.dataset.act,el.dataset.id)});
document.addEventListener('change',e=>{if(e.target.id==='unit-selector'){selectedUnit=e.target.value;e.target.blur();render()}if(e.target.id==='group-filter'){groupFilter=e.target.value;e.target.blur();render()}if(e.target.id==='role'){localStorage.setItem('mes-role',e.target.value);render()}if(e.target.id==='operator')localStorage.setItem('mes-operator',e.target.value)});
document.addEventListener('input',e=>{if(e.target.id==='search'){filter=e.target.value;const position=e.target.selectionStart;e.target.blur();render();$('#search').focus();$('#search').setSelectionRange(position,position)}});
document.addEventListener('submit',e=>{if(e.target.id==='feedback-form')submit('feedback')(e)});
$('#role').value=localStorage.getItem('mes-role')||'operator';$('#operator').value=localStorage.getItem('mes-operator')||'';$('#close-modal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close()});setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})+' KST (+09:00)',1000);refresh();setInterval(refresh,3000);
